### ISSUE TITLE
Endpoints Not Getting Captured

### ISSUE THREAD

**Issue by prakhilKS** [swagger-autogen/swagger-autogen#230]
Hi,

paths object is empty as API endpoints are not getting captured
Below is the repo link.

**https://github.dev/prakhilKS/mass-backend**

Start the project:
`npm i`
`npm run swagger`

**Comment by davibaltar** [comment]
Hi @prakhilKS. Thank you for opening the issue and send a sample code. 

Probably the problem it's because of the `const rootFile=require('./index')`. The lib receive in the `endpointsFiles` parameter a path (type string) to the file. So, instead of:

```js
const rootFile=require('./index')
const endpointsFiles = [rootFile];
```

try to do:

```js
const endpointsFiles = ['./src/index.ts'];
```

here it works for me, but try there and let me know if the problem persists, please.

**Comment by prakhilKS** [comment]
Thanks @davibaltar, it works but swagger-output.json is not modifying when I am updating swagger comments in the function.

Also where should I put swagger-output.json file so that I can easily run `npx ts-node ./src/index"` to have the updated swagger UI as it is not working right now.

**Expected:** 
On hitting `npx ts-node ./src/index"` , it should render updated swagger UI without relying on the build folder

**Comment by davibaltar** [comment]
Sorry for the delay. But, using TS I don't know a way to do that. I'll keep this issue opened so that if someone knows how to do that, maybe it can help you.
